# Generated by Django 6.1.1 on 2026-10-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_telemetry_options_and_more'),
        ('core', '0002_profile_city_profile_full_name'),
        ('waste', '0003_rename_category_pickuprequest_e_waste_category_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alert',
            name='core_alert_is_reso_f19e7a_idx',
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('fill_level', 'Fill Level (80%+)'), ('device_offline', 'Device Offline'), ('high_temperature', 'High Temperature'), ('system', 'System')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_active'], name='core_alert_is_acti_2b5542_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['bin', 'is_active'], name='core_alert_bin_id_d7fca8_idx'),
        ),
        migrations.RemoveField(
            model_name='alert',
            name='is_resolved',
        ),
    ]
