# Generated by Django 6.1.1 on 2026-10-02 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_alert_core_alert_is_reso_f19e7a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, help_text='Collector/employee ID, e.g. COL-001', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_collector_active',
            field=models.BooleanField(default=True, help_text='Inactive collectors cannot receive new tasks.'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('collector', 'Collector')], default='user', help_text='USER = normal resident, COLLECTOR = collection team member', max_length=20),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['role'], name='core_profil_role_0122c2_idx'),
        ),
    ]
