# Generated by Django 6.1.1 on 2026-10-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_employee_id_profile_is_collector_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('fill_level', 'Fill Level (80%+)'), ('device_offline', 'Bin Unavailable'), ('high_temperature', 'High Temperature'), ('system', 'System')], max_length=20),
        ),
    ]
