"""Core models: user profile + system alerts.

Why these live in `core`:
- Profile extends Django's built-in User without replacing it (simplest auth).
- Alert is cross-cutting (bins, pickups, system) so it belongs in the shared app.
"""
from django.conf import settings
from django.db import models


class Profile(models.Model):
    """One-to-one extension of Django's User for ReCircuit users."""

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='profile'
    )
    phone = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Profile({self.user.username})'


class Alert(models.Model):
    """System alert generated by bin thresholds, offline devices, etc."""

    class AlertType(models.TextChoices):
        BIN_FULL = 'bin_full', 'Bin Full (80%+)'
        DEVICE_OFFLINE = 'device_offline', 'Device Offline'
        HIGH_TEMP = 'high_temp', 'High Temperature'
        PICKUP_DELAYED = 'pickup_delayed', 'Pickup Delayed'
        SYSTEM = 'system', 'System'

    class Severity(models.TextChoices):
        INFO = 'info', 'Info'
        WARNING = 'warning', 'Warning'
        CRITICAL = 'critical', 'Critical'

    alert_type = models.CharField(max_length=20, choices=AlertType.choices)
    severity = models.CharField(
        max_length=10, choices=Severity.choices, default=Severity.INFO
    )
    # Nullable links — an alert may relate to a bin and/or a pickup.
    # String references avoid circular imports between apps.
    bin = models.ForeignKey(
        'bins.SmartBin',
        null=True, blank=True,
        on_delete=models.SET_NULL, related_name='alerts',
    )
    pickup = models.ForeignKey(
        'waste.PickupRequest',
        null=True, blank=True,
        on_delete=models.SET_NULL, related_name='alerts',
    )
    message = models.TextField()
    is_resolved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['is_resolved']),
        ]

    def __str__(self):
        return f'[{self.severity}] {self.alert_type}: {self.message[:50]}'
