# Generated by Django 6.1.1 on 2026-10-01 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('category', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('other', 'Other Electronics')], default='other', max_length=20)),
                ('estimated_weight', models.FloatField(help_text='Estimated kg')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(default='Morning (9AM-12PM)', help_text='e.g. Morning (9AM-12PM)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('collected', 'Collected'), ('processing', 'Processing'), ('recycled', 'Recycled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('collected', 'Collected'), ('processing', 'Processing'), ('recycled', 'Recycled')], default='assigned', max_length=20)),
                ('collector_name', models.CharField(blank=True, max_length=100)),
                ('collected_weight', models.FloatField(blank=True, help_text='Actual kg', null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='bins.smartbin')),
                ('pickup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collections', to='waste.pickuprequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecyclingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_weight', models.FloatField(help_text='kg received at facility')),
                ('category', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('other', 'Other Electronics')], default='other', max_length=20)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('sorting', 'Sorting'), ('dismantling', 'Dismantling'), ('processing', 'Processing'), ('completed', 'Completed')], default='received', max_length=20)),
                ('recyclable_material', models.FloatField(default=0.0)),
                ('reusable_material', models.FloatField(default=0.0)),
                ('hazardous_material', models.FloatField(default=0.0)),
                ('residual_waste', models.FloatField(default=0.0)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recycling', to='waste.collection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EwasteSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('other', 'Other Electronics')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('estimated_weight', models.FloatField(help_text='Estimated kg')),
                ('condition', models.CharField(choices=[('working', 'Working'), ('repairable', 'Repairable'), ('dead', 'Dead / Not Working'), ('damaged', 'Physically Damaged')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('scheduled', 'Scheduled for Pickup'), ('collected', 'Collected'), ('recycled', 'Recycled')], default='submitted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='waste_ewast_user_id_c11f1c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['status'], name='waste_picku_status_92fad7_idx'),
        ),
        migrations.AddIndex(
            model_name='pickuprequest',
            index=models.Index(fields=['user', '-created_at'], name='waste_picku_user_id_929501_idx'),
        ),
    ]
