# Generated by Django 6.1.1 on 2026-10-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ewastesubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ewastesubmission',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('television', 'Television'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ewastesubmission',
            name='condition',
            field=models.CharField(choices=[('working', 'Working'), ('damaged', 'Damaged'), ('non_functional', 'Non-functional'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ewastesubmission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('collected', 'Collected'), ('processing', 'Processing'), ('recycled', 'Recycled')], default='submitted', max_length=20),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('television', 'Television'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclingrecord',
            name='category',
            field=models.CharField(choices=[('smartphone', 'Smartphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('battery', 'Battery'), ('charger', 'Charger'), ('cable', 'Cable'), ('monitor', 'Monitor'), ('television', 'Television'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
