# Generated by Django 6.1.1 on 2026-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste', '0002_ewastesubmission_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='category',
            new_name='e_waste_category',
        ),
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='address',
            new_name='pickup_address',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
