# Generated by Django 6.1.1 on 2026-10-02 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_telemetry_options_and_more'),
        ('core', '0004_profile_employee_id_profile_is_collector_active_and_more'),
        ('waste', '0003_rename_category_pickuprequest_e_waste_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('critical', 'Critical')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('fill_level_at_creation', models.FloatField(blank=True, null=True)),
                ('weight_at_creation', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Collector user (must have collector role).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_from_alert', models.ForeignKey(blank=True, help_text='Fill alert that triggered this task, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='core.alert')),
                ('pickup_request', models.ForeignKey(blank=True, help_text='Set when the task came from a user pickup request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='waste.pickuprequest')),
                ('smart_bin', models.ForeignKey(blank=True, help_text='Set when the task came from a smart-bin fill alert.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_tasks', to='bins.smartbin')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='waste_colle_status_945fbf_idx'), models.Index(fields=['priority'], name='waste_colle_priorit_84b845_idx'), models.Index(fields=['assigned_to', 'status'], name='waste_colle_assigne_96c58a_idx'), models.Index(fields=['smart_bin', 'status'], name='waste_colle_smart_b_0194d6_idx'), models.Index(fields=['pickup_request', 'status'], name='waste_colle_pickup__5586e3_idx'), models.Index(fields=['-created_at'], name='waste_colle_created_c74aee_idx')],
            },
        ),
    ]
