# Generated by Django 6.1.1 on 2026-10-02 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0002_alter_telemetry_options_and_more'),
        ('waste', '0004_collectiontask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Secret single-use token embedded in the submit step.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='actual_weight',
            field=models.FloatField(blank=True, help_text='Verified kg (set by operations)', null=True),
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='pickup_request',
            field=models.ForeignKey(blank=True, help_text='Pickup this submission rides along with, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='waste.pickuprequest'),
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='smart_bin',
            field=models.ForeignKey(blank=True, help_text='Bin used for SMART_BIN submissions (null for PICKUP).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='bins.smartbin'),
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='submission_method',
            field=models.CharField(choices=[('smart_bin', 'Smart Bin'), ('pickup', 'Pickup')], default='pickup', help_text='SMART_BIN = deposited at a bin, PICKUP = doorstep collection', max_length=10),
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('qr_verified', 'QR Verified')], default='pending', help_text='QR_VERIFIED only via a valid QR deposit session.', max_length=15),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='collection_task',
            field=models.ForeignKey(blank=True, help_text='Collection task that brought the material in, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycling_records', to='waste.collectiontask'),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='recycled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='recycling_partner',
            field=models.CharField(blank=True, default='', help_text='Internal facility/team handling recycling (no external claims).', max_length=120),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='submission',
            field=models.ForeignKey(blank=True, help_text='Submission being recycled (Day 7 pipeline).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling_records', to='waste.ewastesubmission'),
        ),
        migrations.AddField(
            model_name='recyclingrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recyclingrecord',
            name='collection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recycling', to='waste.collection'),
        ),
        migrations.AlterField(
            model_name='recyclingrecord',
            name='processing_status',
            field=models.CharField(choices=[('received', 'Received'), ('sorting', 'Sorting'), ('dismantling', 'Dismantling'), ('processing', 'Processing'), ('completed', 'Completed'), ('awaiting_processing', 'Awaiting Processing'), ('recycled', 'Recycled')], default='received', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recyclingrecord',
            index=models.Index(fields=['processing_status'], name='waste_recyc_process_33cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclingrecord',
            index=models.Index(fields=['submission', '-created_at'], name='waste_recyc_submiss_a7cef4_idx'),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='smart_bin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_sessions', to='bins.smartbin'),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_session', to='waste.ewastesubmission'),
        ),
        migrations.AddField(
            model_name='depositsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ewastesubmission',
            name='deposit_session',
            field=models.ForeignKey(blank=True, help_text='QR deposit session this submission was created from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='waste.depositsession'),
        ),
        migrations.AddIndex(
            model_name='ewastesubmission',
            index=models.Index(fields=['status'], name='waste_ewast_status_9ef0bb_idx'),
        ),
        migrations.AddIndex(
            model_name='ewastesubmission',
            index=models.Index(fields=['verification_status'], name='waste_ewast_verific_598f60_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['token'], name='waste_depos_token_460ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='depositsession',
            index=models.Index(fields=['user', '-created_at'], name='waste_depos_user_id_2d5798_idx'),
        ),
    ]
