# Generated by Django 6.1.1 on 2026-10-01 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(help_text='Unique device ID, e.g. ECO-BIN-001 (matches ESP32 device_id)', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fill_percentage', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0, help_text='Kilograms')),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('is_online', models.BooleanField(default=True)),
                ('data_source', models.CharField(choices=[('real', 'Real Device'), ('simulated', 'Simulated')], default='simulated', help_text='REAL = ESP32 hardware, SIMULATED = demo generator', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['bin_id'],
                'indexes': [models.Index(fields=['bin_id'], name='bins_smartb_bin_id_d9511c_idx'), models.Index(fields=['is_online'], name='bins_smartb_is_onli_625c29_idx')],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_level', models.FloatField(help_text='Fill % 0-100')),
                ('weight', models.FloatField(help_text='Kilograms')),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('is_simulated', models.BooleanField(default=True, help_text='True = demo generator, False = real ESP32 hardware')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='bins.smartbin')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['bin', '-recorded_at'], name='bins_teleme_bin_id_69bf28_idx')],
            },
        ),
    ]
