# Generated by Django 6.1.1 on 2026-10-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetry',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='telemetry',
            name='bins_teleme_bin_id_69bf28_idx',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='bin',
            new_name='smart_bin',
        ),
        migrations.RenameField(
            model_name='telemetry',
            old_name='recorded_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='smartbin',
            name='fill_percentage',
        ),
        migrations.AddField(
            model_name='smartbin',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='fill_level',
            field=models.FloatField(default=0.0, help_text='Fill % 0-100'),
        ),
        migrations.AddField(
            model_name='telemetry',
            name='data_source',
            field=models.CharField(choices=[('real', 'Real Device'), ('simulated', 'Simulated')], default='simulated', help_text='REAL = ESP32 hardware, SIMULATED = demo generator', max_length=10),
        ),
        migrations.AddIndex(
            model_name='telemetry',
            index=models.Index(fields=['smart_bin', '-timestamp'], name='bins_teleme_smart_b_d86ee0_idx'),
        ),
        migrations.RemoveField(
            model_name='telemetry',
            name='is_simulated',
        ),
    ]
